- name: Install requirement
  hosts: server
  become: yes
  gather_facts: no
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
 
- name: LAMP
  hosts: server
  become: yes
  pre_tasks:
    - name: Make sure PHP 7.0 removed
      apt:
        name: "php7.*"
        state: absent
  roles:
    - role: geerlingguy.mysql
    - role: geerlingguy.apache
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: phpconfig

- name: Node
  hosts: server
  become: yes
  roles:
    - role: pablocrivella.nvm
